# Resolve
def test_resolve_calls_provider_and_returns_its_result(): ...


def test_resolve_calls_provider_with_its_dependencies_and_returns_its_result(): ...


# Context manager


def test_resolve_with_cm_and_enter_enters_provider_result_and_returns_it(): ...


def test_resolve_with_cm_and_not_enter_not_enter_and_returns_provider_result(): ...


# Lifetimes
def test_resolve_transient_calls_provider_on_each_resolve(): ...


def test_resolve_scoped_calls_provider_once_per_container(): ...


def test_resolve_singleton_calls_provider_once_per_registry(): ...


# Close
def test_close_container_exits_scoped_provider_context_managers(): ...
def test_close_container_exits_transient_provider_context_managers(): ...
def test_close_registry_exits_singleton_provider_context_managers(): ...
